### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by alnavasa** [itemir/signalk-barometer#1]
Question:
Where does it get the values from??

**Comment by itemir** [comment]
You can see it in the source and it is configurable:

https://github.com/itemir/signalk-barometer/blob/main/index.js#L341

**Comment by alnavasa** [comment]
> You can see it in the source and it is configurable:
> 
> https://github.com/itemir/signalk-barometer/blob/main/index.js#L341

well, I can't, can you let me know? is it from local sensors, or website based on location, also, this info might be useful on the README file.

**Comment by itemir** [comment]
It takes it from Signal K so it really depends on how you configured your Signal K server and the sensors on it. If this doesn't resonate, wondering if you are looking at the wrong solution?

**Comment by alnavasa** [comment]
> It takes it from Signal K so it really depends on how you configured your Signal K server and the sensors on it. If this doesn't resonate, wondering if you are looking at the wrong solution?

I am! I don't have baro sensor (yet) I was wondering if this one could get it from cloud services eg:windy.com 

Thanks for your answers!
